In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive



In [ ]:
import pandas as pd

df1 =pd.read_csv("/content/RTW sample AB.csv")
df1.head()

Claim No  Occurrence No  Claim Financial Year  Agency NN Incident Date  \
0  13/005096              1                  2013       7069    01/11/2012   
1  21/013033              1                  2021      63246    29/04/2021   
2  16/005676              1                  2016    2043954    16/11/2015   
3  15/002879              1                  2015      63246    04/09/2014   
4  14/020489              2                  2014      63246    08/05/2014   

  Finalised Date  Total Paid Paid Days Lost Service Start Date  \
0     24/01/2013   $8,580.00          26.01         02/11/2012   
1     10/06/2021     $573.66              2         29/04/2021   
2     04/01/2016     $796.97           2.02         16/11/2015   
3     18/02/2015   $5,570.19             26         05/09/2014   
4     29/01/2016  $35,406.63          75.09         03/10/2014   

  Service End Date  ...                                      Mechanism  \
0       18/12/2012  ...  Muscular stress-lift, carry, put down objects   
1       30/04/2021  ...                        Falls on the same level   
2       17/11/2015  ...         Being assaulted by a person or persons   
3       10/10/2014  ...        Muscular stress with no objects handled   
4       12/01/2015  ...                        Falls on the same level   

                                          Nature  \
0      Sprains and strains of joints and muscles   
1  Open wound not including traumatic amputation   
2  Open wound not including traumatic amputation   
3      Sprains and strains of joints and muscles   
4      Sprains and strains of joints and muscles   

                                              Major  \
0  Intermediate Clerical, Sales and Service Workers   
1  Intermediate Clerical, Sales and Service Workers   
2                           Associate Professionals   
3  Intermediate Clerical, Sales and Service Workers   
4                 Tradespersons and Related Workers   

                            Occupation    Gender Date of Birth Days to RTW  \
0              Personal Care Assistant  Male        05/11/1956          46   
1  Teachers Aide (Education Assistant)  Female      18/08/1971           1   
2             Residential Care Officer  Male        07/07/1967           1   
3  Teachers Aide (Education Assistant)  Male        29/07/1973          35   
4                     General Gardener  Male        06/02/1951         101   

   RTW Category Age at Accident Date Settled  
0  RTW 13 Weeks                   55       N  
1  RTW 13 Weeks                   49       N  
2  RTW 13 Weeks                   48       N  
3  RTW 13 Weeks                   41       N  
4  RTW 26 Weeks                   63       N  

[5 rows x 25 columns]

# New section

In [ ]:
df1.shape

(23139, 25)

In [ ]:
df1.dtypes

Claim No                 object
Occurrence No             int64
Claim Financial Year      int64
Agency NN                 int64
Incident Date            object
Finalised Date           object
Total Paid               object
Paid Days Lost           object
Service Start Date       object
Service End Date         object
Injury Agency Group      object
Bodily Location Group    object
Mechanism Group          object
Nature Group             object
Bodily Location          object
Mechanism                object
Nature                   object
Major                    object
Occupation               object
Gender                   object
Date of Birth            object
Days to RTW               int64
RTW Category             object
Age at Accident Date      int64
Settled                  object
dtype: object

In [ ]:
df1.isnull().sum()

Claim No                   0
Occurrence No              0
Claim Financial Year       0
Agency NN                  0
Incident Date              0
Finalised Date             0
Total Paid                 0
Paid Days Lost             0
Service Start Date       475
Service End Date         475
Injury Agency Group        0
Bodily Location Group      0
Mechanism Group            0
Nature Group               0
Bodily Location            0
Mechanism                  0
Nature                     0
Major                      0
Occupation                 0
Gender                     0
Date of Birth              1
Days to RTW                0
RTW Category               0
Age at Accident Date       0
Settled                    0
dtype: int64

In [ ]:
df2=df1.drop(['Claim No','Claim Financial Year'],axis=1)

In [ ]:
df2['Total Paid']=df2['Total Paid'].str.replace("$","")
df2['Total Paid']=df2['Total Paid'].str.replace(",","")


<ipython-input-9-8db09d7a9cb5>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df2['Total Paid']=df2['Total Paid'].str.replace("$","")


In [ ]:
df2['Total Paid'] = df2['Total Paid'].apply(lambda x : float(x))

In [ ]:
df2['Paid Days Lost'].value_counts()

1         1140
2         1101
3          773
4          573
5          492
          ... 
497.6        1
53.06        1
349.66       1
79.33        1
124.3        1
Name: Paid Days Lost, Length: 7392, dtype: int64

In [ ]:
df2['Paid Days Lost']=df2['Paid Days Lost'].str.replace(",","")
df2['Paid Days Lost'] = df2['Paid Days Lost'].apply(lambda x : float(x))

In [ ]:
df2['Injury Agency Group'].value_counts()

Animal, Human and Biological Agencies              7098
Non-powered Handtools, Appliances and Equipment    5988
Environmental Agencies                             3789
Other and Unspecified Agencies                     2405
Mobile Plant and Transport                         1174
Materials and Substances                           1143
Powered Equipment, Tools and Appliances            1034
Machinery and (Mainly) Fixed Plant                  321
Chemicals and Chemical Products                     187
Name: Injury Agency Group, dtype: int64

In [ ]:
df2['Injury Agency Group']=df2['Injury Agency Group'].apply(lambda x : 'Other' if x=='Powered Equipment, Tools and Appliances' or x=='Machinery and (Mainly) Fixed Plant' or x=='Chemicals and Chemical Products' else x)

In [ ]:
df2['Injury Agency Group'].value_counts()

Animal, Human and Biological Agencies              7098
Non-powered Handtools, Appliances and Equipment    5988
Environmental Agencies                             3789
Other and Unspecified Agencies                     2405
Other                                              1542
Mobile Plant and Transport                         1174
Materials and Substances                           1143
Name: Injury Agency Group, dtype: int64

In [ ]:
df2['Bodily Location Group'].value_counts()

Upper Limbs                                    6216
Lower Limbs                                    5255
Trunk (inc. Back)                              4450
Multiple Locations                             2799
Non-physical Locations (Psychological)         2075
Head                                           1637
Neck                                            574
Systemic Locations (eg. Nervous, Digestive)     107
Unspecified Locations                            26
Name: Bodily Location Group, dtype: int64

In [ ]:
df2['Bodily Location Group']=df2['Bodily Location Group'].apply(lambda x : 'Other' if x=='Unspecified Locations' or x=='Systemic Locations (eg. Nervous, Digestive)' or x=='Neck' or x=='Non-physical Locations (Psychological)'
or x=='Head'
 else x)

In [ ]:
df2['Bodily Location Group'].value_counts()

Upper Limbs           6216
Lower Limbs           5255
Trunk (inc. Back)     4450
Other                 4419
Multiple Locations    2799
Name: Bodily Location Group, dtype: int64

In [ ]:
df2['Mechanism Group'].value_counts()

Body Stressing                                8358
Falls, Slips and Trips of a Person            5637
Being Hit by Moving Objects                   5016
Mental Stress                                 1909
Hitting Objects with a Part of the Body       1118
Other and Unspecified Mechanisms of Injury     328
Chemicals and Other Substances                 295
Heat, Radiation and Electricity                246
Biological Factors                             205
Sound and Pressure                              27
Name: Mechanism Group, dtype: int64

In [ ]:
df2['Mechanism Group']=df2['Mechanism Group'].apply(lambda x : 'Other' if x=='Sound and Pressure' or x=='Biological Factors' or x=='Heat, Radiation and Electricity' or x=='Chemicals and Other Substances'
or x=='Other and Unspecified Mechanisms of Injury' or x=='Hitting Objects with a Part of the Body' or x=='Mental Stress'
 else x)

In [ ]:
df2['Mechanism Group'].value_counts()

Body Stressing                        8358
Falls, Slips and Trips of a Person    5637
Being Hit by Moving Objects           5016
Other                                 4128
Name: Mechanism Group, dtype: int64

In [ ]:
df2['Nature Group'].value_counts()


Sprains, Strains and Dislocations               10132
Musculoskeletal System and Connective Tissue     3525
Contusion and Crushing                           2476
Mental Disorders                                 2197
Fractures                                        1551
All Other Diseases                               1126
Open Wound                                        966
Superficial Injury                                796
Burns                                             232
Foreign body, Ear, Eye, Nose, Respiratory          88
Multiple Injuries                                  50
Name: Nature Group, dtype: int64

In [ ]:
df2['Nature Group']=df2['Nature Group'].apply(lambda x : 'Other'  if  x!='Sprains, Strains and Dislocations' else x)

In [ ]:
df2['Nature Group'].value_counts()

Other                                13007
Sprains, Strains and Dislocations    10132
Name: Nature Group, dtype: int64

In [ ]:
df2['Major'].value_counts()
df2['Major']=df2['Major'].apply(lambda x : 'Professionals' if x=='Professionals' or x=='Associate Professionals' else x )
df2['Major']=df2['Major'].apply(lambda x : x if x=='Professionals' or x=='Intermediate Clerical, Sales and Service Workers' else 'Others' )

In [ ]:
df2['Major'].value_counts()

Professionals                                       9607
Intermediate Clerical, Sales and Service Workers    8159
Others                                              5373
Name: Major, dtype: int64

In [ ]:
df2['Gender'].value_counts()
df2['Gender']=df2['Gender'].str.strip()
df3 = df2[df2['Gender'] != 'Unknown']

In [ ]:
df3.columns

Index(['Occurrence No', 'Agency NN', 'Incident Date', 'Finalised Date',
       'Total Paid', 'Paid Days Lost', 'Service Start Date',
       'Service End Date', 'Injury Agency Group', 'Bodily Location Group',
       'Mechanism Group', 'Nature Group', 'Bodily Location', 'Mechanism',
       'Nature', 'Major', 'Occupation', 'Gender', 'Date of Birth',
       'Days to RTW', 'RTW Category', 'Age at Accident Date', 'Settled'],
      dtype='object')

In [ ]:
df3['Gender'].value_counts()

Female    14492
Male       8646
Name: Gender, dtype: int64

In [ ]:

columns=['Injury Agency Group', 'Bodily Location Group','Mechanism Group','Nature Group','Major','Gender']
for i in columns:
  dummies = pd.get_dummies(i +'_'+ df3[i])
  df3=pd.concat([df3,dummies],axis=1)

In [ ]:
df3.columns

Index(['Occurrence No', 'Agency NN', 'Incident Date', 'Finalised Date',
       'Total Paid', 'Paid Days Lost', 'Service Start Date',
       'Service End Date', 'Injury Agency Group', 'Bodily Location Group',
       'Mechanism Group', 'Nature Group', 'Bodily Location', 'Mechanism',
       'Nature', 'Major', 'Occupation', 'Gender', 'Date of Birth',
       'Days to RTW', 'RTW Category', 'Age at Accident Date', 'Settled',
       'Injury Agency Group_Animal, Human and Biological Agencies',
       'Injury Agency Group_Environmental Agencies',
       'Injury Agency Group_Materials and Substances',
       'Injury Agency Group_Mobile Plant and Transport',
       'Injury Agency Group_Non-powered Handtools, Appliances and Equipment',
       'Injury Agency Group_Other',
       'Injury Agency Group_Other and Unspecified Agencies',
       'Bodily Location Group_Lower Limbs',
       'Bodily Location Group_Multiple Locations',
       'Bodily Location Group_Other',
       'Bodily Location Group_Trunk (

In [ ]:
df3.drop(['Injury Agency Group', 'Bodily Location Group','Mechanism Group','Nature Group','Major','Gender'],axis=1)

Occurrence No  Agency NN Incident Date Finalised Date  Total Paid  \
0                  1       7069    01/11/2012     24/01/2013     8580.00   
1                  1      63246    29/04/2021     10/06/2021      573.66   
2                  1    2043954    16/11/2015     04/01/2016      796.97   
3                  1      63246    04/09/2014     18/02/2015     5570.19   
4                  2      63246    08/05/2014     29/01/2016    35406.63   
...              ...        ...           ...            ...         ...   
23134              1      63246    22/03/2022     26/06/2022     1470.12   
23135              1      63246    06/08/2015     09/11/2015     4730.55   
23136              1    2623845    27/07/2018     14/09/2018      943.10   
23137              1    2253554    21/03/2013     28/02/2014     2062.57   
23138              1    2623920    04/11/2021     28/11/2022   103955.89   

       Paid Days Lost Service Start Date Service End Date  \
0               26.01         02/11/2012       18/12/2012   
1                2.00         29/04/2021       30/04/2021   
2                2.02         16/11/2015       17/11/2015   
3               26.00         05/09/2014       10/10/2014   
4               75.09         03/10/2014       12/01/2015   
...               ...                ...              ...   
23134            6.00         23/03/2022       30/03/2022   
23135            5.00         10/08/2015       16/08/2015   
23136            2.00         30/07/2018       02/08/2018   
23137            3.00         22/03/2013       24/03/2013   
23138          124.30         21/11/2021       15/09/2022   

                    Bodily Location  \
0                           Stomach   
1      Head - unspecified locations   
2                              Face   
3                              Knee   
4                          Shoulder   
...                             ...   
23134     Back - other and multiple   
23135                    Lower back   
23136                        Breast   
23137                         Ankle   
23138                          Ribs   

                                           Mechanism  ...  \
0      Muscular stress-lift, carry, put down objects  ...   
1                            Falls on the same level  ...   
2             Being assaulted by a person or persons  ...   
3            Muscular stress with no objects handled  ...   
4                            Falls on the same level  ...   
...                                              ...  ...   
23134          Muscular stress while handling object  ...   
23135          Muscular stress while handling object  ...   
23136         Being assaulted by a person or persons  ...   
23137                        Falls on the same level  ...   
23138             Being hit by a person accidentally  ...   

      Mechanism Group_Body Stressing  \
0                                  1   
1                                  0   
2                                  0   
3                                  1   
4                                  0   
...                              ...   
23134                              1   
23135                              1   
23136                              0   
23137                              0   
23138                              0   

      Mechanism Group_Falls, Slips and Trips of a Person  \
0                                                      0   
1                                                      1   
2                                                      0   
3                                                      0   
4                                                      1   
...                                                  ...   
23134                                                  0   
23135                                                  0   
23136                                                  0   
23137                                                  1   
23138             

In [ ]:
df3.columns

Index(['Occurrence No', 'Agency NN', 'Incident Date', 'Finalised Date',
       'Total Paid', 'Paid Days Lost', 'Service Start Date',
       'Service End Date', 'Injury Agency Group', 'Bodily Location Group',
       'Mechanism Group', 'Nature Group', 'Bodily Location', 'Mechanism',
       'Nature', 'Major', 'Occupation', 'Gender', 'Date of Birth',
       'Days to RTW', 'RTW Category', 'Age at Accident Date', 'Settled',
       'Injury Agency Group_Animal, Human and Biological Agencies',
       'Injury Agency Group_Environmental Agencies',
       'Injury Agency Group_Materials and Substances',
       'Injury Agency Group_Mobile Plant and Transport',
       'Injury Agency Group_Non-powered Handtools, Appliances and Equipment',
       'Injury Agency Group_Other',
       'Injury Agency Group_Other and Unspecified Agencies',
       'Bodily Location Group_Lower Limbs',
       'Bodily Location Group_Multiple Locations',
       'Bodily Location Group_Other',
       'Bodily Location Group_Trunk (

In [ ]:
df5=df3.drop (['Occurrence No',  'Incident Date', 'Finalised Date',
       'Service Start Date', 'Service End Date', 'Injury Agency Group', 'Bodily Location Group',
       'Mechanism Group', 'Nature Group', 'Bodily Location', 'Mechanism',
       'Nature', 'Major', 'Occupation', 'Gender', 'Date of Birth',
        'Settled'
       ],axis=1)

In [ ]:
df5.columns

Index(['Agency NN', 'Total Paid', 'Paid Days Lost', 'Days to RTW',
       'RTW Category', 'Age at Accident Date',
       'Injury Agency Group_Animal, Human and Biological Agencies',
       'Injury Agency Group_Environmental Agencies',
       'Injury Agency Group_Materials and Substances',
       'Injury Agency Group_Mobile Plant and Transport',
       'Injury Agency Group_Non-powered Handtools, Appliances and Equipment',
       'Injury Agency Group_Other',
       'Injury Agency Group_Other and Unspecified Agencies',
       'Bodily Location Group_Lower Limbs',
       'Bodily Location Group_Multiple Locations',
       'Bodily Location Group_Other',
       'Bodily Location Group_Trunk (inc. Back)',
       'Bodily Location Group_Upper Limbs',
       'Mechanism Group_Being Hit by Moving Objects',
       'Mechanism Group_Body Stressing',
       'Mechanism Group_Falls, Slips and Trips of a Person',
       'Mechanism Group_Other', 'Nature Group_Other',
       'Nature Group_Sprains, Strains and

In [ ]:
df5.dtypes

Agency NN                                                                int64
Total Paid                                                             float64
Paid Days Lost                                                         float64
Days to RTW                                                              int64
RTW Category                                                            object
Age at Accident Date                                                     int64
Injury Agency Group_Animal, Human and Biological Agencies                uint8
Injury Agency Group_Environmental Agencies                               uint8
Injury Agency Group_Materials and Substances                             uint8
Injury Agency Group_Mobile Plant and Transport                           uint8
Injury Agency Group_Non-powered Handtools, Appliances and Equipment      uint8
Injury Agency Group_Other                                                uint8
Injury Agency Group_Other and Unspecified Agencies  

In [ ]:
df5['RTW Category'].value_counts()

RTW 13 Weeks        15112
Not RTW 26 Weeks     5535
RTW 26 Weeks         2491
Name: RTW Category, dtype: int64

**Drop the columns with null values**

In [ ]:
df5.isna().sum()

Agency NN                                                              0
Total Paid                                                             0
Paid Days Lost                                                         0
Days to RTW                                                            0
RTW Category                                                           0
Age at Accident Date                                                   0
Injury Agency Group_Animal, Human and Biological Agencies              0
Injury Agency Group_Environmental Agencies                             0
Injury Agency Group_Materials and Substances                           0
Injury Agency Group_Mobile Plant and Transport                         0
Injury Agency Group_Non-powered Handtools, Appliances and Equipment    0
Injury Agency Group_Other                                              0
Injury Agency Group_Other and Unspecified Agencies                     0
Bodily Location Group_Lower Limbs                  

In [ ]:
x = df5.drop(['RTW Category','Paid Days Lost','Days to RTW','Total Paid'],axis=1)
y = df5['RTW Category']

In [ ]:
x.head()

Agency NN  Age at Accident Date  \
0       7069                    55   
1      63246                    49   
2    2043954                    48   
3      63246                    41   
4      63246                    63   

   Injury Agency Group_Animal, Human and Biological Agencies  \
0                                                  0           
1                                                  0           
2                                                  1           
3                                                  1           
4                                                  0           

   Injury Agency Group_Environmental Agencies  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           1   

   Injury Agency Group_Materials and Substances  \
0                                             0   
1                                             0   
2                                             0   
3                                             0   
4                                             0   

   Injury Agency Group_Mobile Plant and Transport  \
0                                               1   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   Injury Agency Group_Non-powered Handtools, Appliances and Equipment  \
0                                                  0                     
1                                                  1                     
2                                                  0                     
3                                                  0                     
4                                                  0                     

   Injury Agency Group_Other  \
0                          0   
1                          0   
2                          0   
3                          0   
4                          0   

   Injury Agency Group_Other and Unspecified Agencies  \
0                                                  0    
1                                                  0    
2                                                  0    
3                                                  0    
4                                                  0    

   Bodily Location Group_Lower Limbs  ...  Mechanism Group_Body Stressing  \
0                                  0  ...                               1   
1                                  0  ...                               0   
2                                  0  ...                               0   
3                                  1  ...                               1   
4                                  0  ...                               0   

   Mechanism Group_Falls, Slips and Trips of a Person  Mechanism Group_Other  \
0                                                  0                       0   
1                                                  1                       0   
2                                                  0                       0   
3                                                  0                       0   
4                                                  1                       0   

   Nature Group_Other  Nature Group_Sprains, Strains and Dislocations  \
0                   0                                               1   
1                   1                                               0   
2                   1                                               0   
3                   0                                               1   
4                   0                                               1   

   Major_Intermediate Clerical, Sales and Service Workers  Major_Others  \
0                            

In [ ]:
#from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it
#randomsampler = RandomOverSampler()

#x,y = randomsampler.fit_resample(X,Y)

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model1 = GaussianNB()

In [ ]:
model1.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
print(model1.score(xtrain,ytrain))
print(model1.score(xtest,ytest))

0.656024894830865
0.6444252376836647


In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(ytrain, model1.predict(xtrain)))

print(confusion_matrix(ytest, model1.predict(xtest)))

[[    0  4072     0]
 [    0 11384     0]
 [    0  1897     0]]
[[   0 1463    0]
 [   0 3728    0]
 [   0  594    0]]


In [ ]:
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
print(classification_report(ytrain, model1.predict(xtrain)))
print(classification_report(ytest, model1.predict(xtest)))

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                  precision    recall  f1-score   support

Not RTW 26 Weeks       0.00      0.00      0.00      4072
    RTW 13 Weeks       0.66      1.00      0.79     11384
    RTW 26 Weeks       0.00      0.00      0.00      1897

        accuracy                           0.66     17353
       macro avg       0.22      0.33      0.26     17353
    weighted avg       0.43      0.66      0.52     17353

                  precision    recall  f1-score   support

Not RTW 26 Weeks       0.00      0.00      0.00      1463
    RTW 13 Weeks       0.64      1.00      0.78      3728
    RTW 26 Weeks       0.00      0.00      0.00       594

        accuracy                           0.64      5785
       macro avg       0.21      0.33      0.26      5785
    weighted avg       0.42      0.64      0.51      5785



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classificat

**Drop the rows with null Values**

In [ ]:
from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it
randomsampler = RandomOverSampler()

x,y = randomsampler.fit_resample(x,y)

In [ ]:
x = df5.drop(['RTW Category','Total Paid','Paid Days Lost'],axis=1)
y = df5['RTW Category']

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y)

In [ ]:
from sklearn.naive_bayes import GaussianNB
model2 = GaussianNB()

In [ ]:
model2.fit(xtrain,ytrain)

GaussianNB()

In [ ]:
print(model2.score(xtrain,ytrain))
print(model2.score(xtest,ytest))

0.9550509998271193
0.9571305099394987


In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(ytrain, model2.predict(xtrain)))

print(confusion_matrix(ytest, model2.predict(xtest)))

[[ 3824     0   365]
 [    0 11273     0]
 [    0   415  1476]]
[[1228    0  118]
 [   0 3839    0]
 [   0  130  470]]


In [ ]:
print(classification_report(ytrain, model2.predict(xtrain)))

print(classification_report(ytest, model2.predict(xtest)))

                  precision    recall  f1-score   support

Not RTW 26 Weeks       1.00      0.91      0.95      4189
    RTW 13 Weeks       0.96      1.00      0.98     11273
    RTW 26 Weeks       0.80      0.78      0.79      1891

        accuracy                           0.96     17353
       macro avg       0.92      0.90      0.91     17353
    weighted avg       0.96      0.96      0.95     17353

                  precision    recall  f1-score   support

Not RTW 26 Weeks       1.00      0.91      0.95      1346
    RTW 13 Weeks       0.97      1.00      0.98      3839
    RTW 26 Weeks       0.80      0.78      0.79       600

        accuracy                           0.96      5785
       macro avg       0.92      0.90      0.91      5785
    weighted avg       0.96      0.96      0.96      5785



In [ ]:
model2.predict(xtrain)

array(['RTW 13 Weeks', 'RTW 13 Weeks', 'RTW 13 Weeks', ...,
       'RTW 26 Weeks', 'RTW 13 Weeks', 'RTW 13 Weeks'], dtype='<U16')

In [ ]:
model2.predict_proba(xtrain)

array([[0.06723997, 0.59582746, 0.33693257],
       [0.01254856, 0.98542909, 0.00202234],
       [0.01635627, 0.97985429, 0.00378944],
       ...,
       [0.08315942, 0.42504048, 0.4918001 ],
       [0.02072696, 0.9597396 , 0.01953344],
       [0.01903551, 0.97769954, 0.00326494]])

**Tuning threshold**
****

In [ ]:
from sklearn.metrics import roc_curve,roc_auc_score
fpr,tpr,thresh = roc_curve(ytrain , model2.predict_proba(xtrain)[: , 1])

ValueError: ignored

In [ ]:
g_val = tpr * (1-fpr)
print(g_val.argmax())

In [ ]:
print(thresh[5002])

In [ ]:
model2.predict_proba(xtrain)[: , 1] > 0.55

In [ ]:
ypredTrainThresh = np.where(model2.predict_proba(xtrain)[: , 1] > 0.55 , 1 , 0)
ypredTestThresh = np.where(model2.predict_proba(xtest)[: , 1] > 0.55 , 1 , 0)

In [ ]:
ypredTrainThresh

In [ ]:
print(confusion_matrix(ytrain, ypredTrainThresh))

In [ ]:
print(confusion_matrix(ytest, ypredTestThresh))

In [ ]:
from sklearn.metrics import classification_report,accuracy_score

In [ ]:
print(classification_report(ytrain, ypredTrainThresh))

In [ ]:
print(classification_report(ytest, ypredTestThresh))

In [ ]:
print(accuracy_score(ytrain, ypredTrainThresh))
print(accuracy_score(ytest, ypredTestThresh))

**Use Random Forest Classifier**

In [ ]:
df5.head()

In [ ]:
from imblearn.over_sampling import RandomOverSampler   #category 1 an 0 are unbalanced so we can makre them equal using it

X2 = df5.drop(['RTW Category','Paid Days Lost','Days to RTW','Total Paid'],axis=1)
Y2 = df5['RTW Category']

randomsampler = RandomOverSampler()

x2,y2 = randomsampler.fit_resample(X2,Y2)

In [ ]:
pd.DataFrame(Y2).value_counts()

In [ ]:
pd.DataFrame(y2).value_counts()

In [ ]:
xtrain2,xtest2,ytrain2,ytest2 = train_test_split(x2,y2,random_state=0)

from sklearn.ensemble import RandomForestClassifier
rmodel1 = RandomForestClassifier(n_estimators=10)

rmodel1.fit(xtrain2,ytrain2)

print(rmodel1.score(xtrain2,ytrain2))
print(rmodel1.score(xtest2,ytest2))


In [ ]:
print(confusion_matrix(ytrain2, rmodel1.predict(xtrain2)))

In [ ]:
print(confusion_matrix(ytest2, rmodel1.predict(xtest2)))

In [ ]:
print(classification_report(ytrain2, rmodel1.predict(xtrain2)))

In [ ]:
print(classification_report(ytest2, rmodel1.predict(xtest2)))

**Neural Network Model**

In [ ]:
x.head()

Agency NN  Days to RTW  Age at Accident Date  \
0       7069           46                    55   
1      63246            1                    49   
2    2043954            1                    48   
3      63246           35                    41   
4      63246          101                    63   

   Injury Agency Group_Animal, Human and Biological Agencies  \
0                                                  0           
1                                                  0           
2                                                  1           
3                                                  1           
4                                                  0           

   Injury Agency Group_Environmental Agencies  \
0                                           0   
1                                           0   
2                                           0   
3                                           0   
4                                           1   

   Injury Agency Group_Materials and Substances  \
0                                             0   
1                                             0   
2                                             0   
3                                             0   
4                                             0   

   Injury Agency Group_Mobile Plant and Transport  \
0                                               1   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   Injury Agency Group_Non-powered Handtools, Appliances and Equipment  \
0                                                  0                     
1                                                  1                     
2                                                  0                     
3                                                  0                     
4                                                  0                     

   Injury Agency Group_Other  \
0                          0   
1                          0   
2                          0   
3                          0   
4                          0   

   Injury Agency Group_Other and Unspecified Agencies  ...  \
0                                                  0   ...   
1                                                  0   ...   
2                                                  0   ...   
3                                                  0   ...   
4                                                  0   ...   

   Mechanism Group_Body Stressing  \
0                               1   
1                               0   
2                               0   
3                               1   
4                               0   

   Mechanism Group_Falls, Slips and Trips of a Person  Mechanism Group_Other  \
0                                                  0                       0   
1                                                  1                       0   
2                                                  0                       0   
3                                                  0                       0   
4                                                  1                       0   

   Nature Group_Other  Nature Group_Sprains, Strains and Dislocations  \
0                   0                                               1   
1                   1                                               0   
2                   1                                               0   
3                   0                                               1   
4                   0                                               1   

   Major_Intermediate Clerical, Sales and Service Workers  Major_Others  \
0                                                  1                  0   
1                                                  1                  0   
2          

In [ ]:
y

0            RTW 13 Weeks
1            RTW 13 Weeks
2            RTW 13 Weeks
3            RTW 13 Weeks
4            RTW 26 Weeks
               ...       
23134        RTW 13 Weeks
23135        RTW 13 Weeks
23136        RTW 13 Weeks
23137        RTW 13 Weeks
23138    Not RTW 26 Weeks
Name: RTW Category, Length: 23138, dtype: object

In [ ]:
randomsampler = RandomOverSampler()

x2,y2 = randomsampler.fit_resample(x,y)

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x2,y2,random_state=0)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scl = MinMaxScaler()

xtrainS = scl.fit(xtrain).transform(xtrain)
xtestS = scl.fit(xtest).transform(xtest)

In [ ]:
xtrain.shape

(34002, 26)

In [ ]:
ytrainE = pd.get_dummies(ytrain)
ytestE = pd.get_dummies(ytest)

In [ ]:
ytrainE

Not RTW 26 Weeks  RTW 13 Weeks  RTW 26 Weeks
36985                 0             0             1
42481                 0             0             1
11291                 0             1             0
499                   1             0             0
12876                 0             1             0
...                 ...           ...           ...
30403                 1             0             0
21243                 0             1             0
42613                 0             0             1
43567                 0             0             1
2732                  0             0             1

[34002 rows x 3 columns]

In [ ]:
from keras import models,layers

model = models.Sequential()                 #Define the sequential model type

model.add(layers.Dense(16 , input_dim = 26))                     #add a hidden layer with 16 neurons to a input layer with 32 neurons

model.add(layers.Dense(8))

model.add(layers.Dense(3, activation='sigmoid'))                 #add a o/p layer with 5 neurons

model.compile(optimizer='sgd' , loss='categorical_crossentropy' , metrics=['accuracy'])

In [ ]:
model.fit(xtrainS , ytrainE , epochs=50,
          validation_data = (xtestS,ytestE))

Epoch 1/50
1063/1063 [==============================] - 3s 2ms/step - loss: 1.0920 - accuracy: 0.3980 - val_loss: 1.0487 - val_accuracy: 0.4579
Epoch 2/50
1063/1063 [==============================] - 2s 2ms/step - loss: 1.0257 - accuracy: 0.4815 - val_loss: 0.9732 - val_accuracy: 0.5541
Epoch 3/50
1063/1063 [==============================] - 2s 2ms/step - loss: 0.9185 - accuracy: 0.5978 - val_loss: 0.8045 - val_accuracy: 0.6875
Epoch 4/50
1063/1063 [==============================] - 2s 2ms/step - loss: 0.7358 - accuracy: 0.7328 - val_loss: 0.6176 - val_accuracy: 0.8253
Epoch 5/50
1063/1063 [==============================] - 2s 2ms/step - loss: 0.5689 - accuracy: 0.8312 - val_loss: 0.4533 - val_accuracy: 0.9265
Epoch 6/50
1063/1063 [==============================] - 2s 2ms/step - loss: 0.4468 - accuracy: 0.8848 - val_loss: 0.4943 - val_accuracy: 0.7753
Epoch 7/50
1063/1063 [==============================] - 2s 2ms/step - loss: 0.3657 - accuracy: 0.8976 - val_loss: 0.3080 - val_accuracy:

In [ ]:
model.evaluate(xtrainS , ytrainE)

1063/1063 [==============================] - 3s 3ms/step - loss: 0.0761 - accuracy: 0.9704


[0.07612498104572296, 0.9703841209411621]

In [ ]:
model.evaluate(xtestS , ytestE)

355/355 [==============================] - 1s 3ms/step - loss: 0.1597 - accuracy: 0.9267


[0.1596696376800537, 0.9266808032989502]

**Predictions**

In [ ]:
xtrainS.shape

(34002, 26)

In [ ]:
xtrainS[67].shape

(26,)

In [ ]:
model.predict(xtrainS[17].reshape(1,-1))

1/1 [==============================] - 0s 19ms/step


array([[5.2472949e-08, 9.9999267e-01, 9.6964025e-01]], dtype=float32)

In [ ]:
np.argmax(model.predict(xtrainS[17].reshape(1,-1)))

1/1 [==============================] - 0s 33ms/step


1

In [ ]:
print(ytrainE.columns)

Index(['Not RTW 26 Weeks', 'RTW 13 Weeks', 'RTW 26 Weeks'], dtype='object')


In [ ]:
print(ytrainE.columns[np.argmax(model.predict(xtrainS[17].reshape(1,-1)))])

1/1 [==============================] - 0s 18ms/step
RTW 13 Weeks


**Classification Report**

In [ ]:
ytrainReal = []
for val in ytrainE.values:
  ytrainReal.append(np.argmax(val))

In [ ]:
ytestReal = []
for val in ytestE.values:
  ytestReal.append(np.argmax(val))

In [ ]:
ytrainPred = []
for pred in model.predict(xtrainS):
  ytrainPred.append(np.argmax(pred))

1063/1063 [==============================] - 1s 1ms/step


In [ ]:
ytestPred = []
for pred in model.predict(xtestS):
  ytestPred.append(np.argmax(pred))

355/355 [==============================] - 0s 1ms/step


In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(ytrainReal , ytrainPred))

              precision    recall  f1-score   support

           0       1.00      0.95      0.98     11383
           1       0.99      0.97      0.98     11273
           2       0.93      0.99      0.96     11346

    accuracy                           0.97     34002
   macro avg       0.97      0.97      0.97     34002
weighted avg       0.97      0.97      0.97     34002



In [ ]:
print(classification_report(ytestReal , ytestPred))

              precision    recall  f1-score   support

           0       0.87      1.00      0.93      3729
           1       1.00      0.93      0.96      3839
           2       0.92      0.85      0.89      3766

    accuracy                           0.93     11334
   macro avg       0.93      0.93      0.93     11334
weighted avg       0.93      0.93      0.93     11334

